[GAIA-1680] Rating buttons renderer
leftshiftone/conveyjs pull request #54
Opened 2020-10-05 14:19 UTC by LoLei

2020-10-06 13:56 UTC, rschluesselbauer requested changes

2020-10-06 13:56 UTC, rschluesselbauer commented on src/lib/renderer/RatingRenderer.ts
> +        EventStream.addListener(EventType.withChannelId(EventType.PUBLISH, channelId), (e) => {
Der Listener tut nichts - brauchen wir ihn also nicht?

2020-10-06 14:34 UTC, LoLei commented on src/lib/support/node.ts
> +    getDataAttribute(qualifier: string): string | null;
Nirgends, ich hab's nur einmal braucht bevor ich's dann wieder verworfen habe. Aber es gibt schon `addDataAttributes` also würd es auch Sinn machen `getDataAttribute` zu supporten?

2020-10-06 14:34 UTC, LoLei commented on src/lib/renderable/container/index.ts
> +    public render(renderer: IRenderer, isNested: boolean, hasRating: boolean = false): HTMLElement {
:heavy_check_mark:

2020-10-06 14:34 UTC, LoLei commented on src/lib/renderable/rating/index.ts
> +        this.setSpecPropertyIfNotDefined("type", "rating");
:heavy_check_mark:

2020-10-06 14:34 UTC, LoLei commented on src/lib/renderable/rating/index.ts
> +        this.likeButtons.get((buttonType + 1) % RatingButtonType.__LENGTH)!.buttonNode.removeClasses("lto-button-last-clicked");
:heavy_check_mark:

2020-10-06 14:34 UTC, LoLei commented on src/lib/renderable/rating/index.ts
> +    private likeButtons: Map<RatingButtonType, RatingButton>;
:heavy_check_mark:

2020-10-06 14:34 UTC, LoLei commented on src/lib/renderable/rating/index.ts
> +    private readonly buttonDislike: INode;
:heavy_check_mark:

2020-10-06 14:34 UTC, LoLei commented on src/lib/renderer/RatingRenderer.ts
> +        EventStream.addListener(EventType.withChannelId(EventType.PUBLISH, channelId), (e) => {
:heavy_check_mark:

2020-10-07 07:21 UTC, ptrcc approved these changes

2020-10-07 07:36 UTC, LoLei commented on src/lib/support/node.ts
> +    getDataAttribute(qualifier: string): string | null;
Ist removed

2020-10-07 07:45 UTC, rschluesselbauer approved these changes

2020-10-07 07:45 UTC, merged